name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run npm test
    runs-on: ubuntu-latest
    steps:
      - name: Step one
      - uses: actions/checkout@v2

      - name: Step two
        run: cd capstone_project/hello-world
      
      - name: Step three
        run: npm test
  
  containerize:
    needs: [test]
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - name: Step one
      - uses: actions/checkout@v2

      - name: Step two
        run: cd capstone_project/hello-world

      - name: Step three
        run: docker build -t hello-world .
         
      
